[package]
name = "swap_wrapper"
version = "0.0.0"

[addresses]
swap_wrapper = "_"

[dependencies]
AptosFramework = { local = "../../../MoviEth/aptos-move/framework/aptos-framework" }
AptosStdlib = { local = "../../../MoviEth/aptos-move/framework/aptos-stdlib" }
coin_wrapper = { local = "../coin-move", addr_subst= { coin_wrapper = "0x5f61e930582ca112420399eaac4d224aba550789bd31dbe3d8835abac4267b06"} }
PancakeSwap = { local = "../pancake-contracts-move/pancake-swap", addr_subst= { pancake = "0x7a526ec5f06a7976caec96614f0db691f53b452424a3897a18a115ddd300c110"} }